# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MDk2ZWFmOWJkY2Y3ZjQ3NGMwMjgzYjdmMGNlOTNlZTM2OTM1MGNmMjIxMGUxNDQ5NmVhYjhjNGMyNmRhOTYwYWFmOGZiODg2YmNhOGEzNWQzZDljNTgzY2JkZWJkZTRiNDExMTliMjc5YzhmNmJlZDFiOTVkMTExNzRiMGJiMDk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
